### PR TITLE
adhoc/dim_teacher_status

### PR DESCRIPTION
**Pull request by allison-code-dot-org**
## Description

Added started_teaching_at field to dim_teacher_status, which is the first started_at date for their active sections that school year. 

## Links

Jira ticket(s): [DATAOPS-474](https://codedotorg.atlassian.net/jira/software/projects/DATAOPS/boards/72/backlog?selectedIssue=DATAOPS-474)

## Testing story

- [ ] Does your change include appropriate tests?
      eg. `not_null`, `unique`

**Note: when submitting a new model for review please make sure the following have been tested:**
1. The model compiles (`dbt compile -m 'your_model'`)
2. The model runs (`dbt run -m 'your_model'`)
3. The model produces accessible data in the DW (`select 1 from 'your_model'`)

## Follow-up work

Any related, outstanding, blocking, or follow-up work:

## Privacy

- [ ] 1.	Does this change involve the collection, use, or sharing of new Personal Data?

- [ ] 2.	Does this change involve a new or changed use or sharing of existing Personal Data?

## PR Checklist:

- [ ] Tests provide adequate coverage
- [x] Privacy and Security impacts have been assessed
- [x] Code adheres to style-guide and is DRY
- [x] Code is well-commented
- [x] New features are translatable or updates will not break up/downstream models
- [ ] Relevant documentation has been added or updated
- [x] Pull Request is labeled appropriately
- [x] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by bakerfranke — APPROVED** [review]
Adds the min start date across all sections/courses taught by this teacher for the school year.  LTGM

**Comment by jordan-springer** [comment]
looks good, get in the habit of doing these kinds of pr's. a lot of requests will be like this where we have just insert 1 new field in a few places. good work!

oh forgot to add tests here and a yml file. I think I'd rather dump the districts+ models into the `/schools` mart. we don't need a new mart for these few models IMO cc @allison-code-dot-org

**Review by jordan-springer — CHANGES_REQUESTED** [review]
add tests and yml, see comments

**Review by jordan-springer — APPROVED** [review]
LGTM!

**Pull request merged**
