### PR TITLE
dim_user_feedback

### PR DESCRIPTION
**Pull request by allison-code-dot-org**
# Description

This model builds dim_user_feedback and the associated upstream base/ staging models associated with AI Tutor. 

`dim_user_feedback` is meant to be a generalizable model for all user feedback to live, regardless of feature. 

Key business requirements/ relevant notes from PMs:
- the format of this feedback should stay the same (always will be thumbs up/down and details) 
- they plan to bring in feedback from more features in the near future that they will want surfaced in trevor (hence the need for a generalizable model)
- they want to be able to segment feedback by school year
- right now, only students give feedback on features, but both students and teachers will give feedback in the future

## Links

Jira ticket(s): [DATAOPS-930](https://codedotorg.atlassian.net/jira/software/projects/DATAOPS/boards/72/backlog?selectedIssue=DATAOPS-930&text=ai)

### CODE REVIEW

**Comment by coryamanda** [comment]
A couple comments for consideration here:
- Given the specification above that they will eventually expect students and teachers to be adding feedback, why not bring in user_type at this stage? 
- I see two other feedback tables that are exposed in Trevor - Redshift. Since you're going through the exercise to make a general version of a feedback table, would it make sense to extend that general version and see whether it works for the other two tables as well? That feels like a good way to test the model's ability to generalize across different types of feedback and it's work we would need to do anyway to deprecate Trevor Redshift. Those are:
1) lti_feedbacks from Ali (ticket here: https://codedotorg.atlassian.net/browse/DATAOPS-633)
2) new_feature_feedbacks from Bryan (ticket here: https://codedotorg.atlassian.net/browse/DATAOPS-738)

**Comment by coryamanda** [comment]
One more comment, and this likely requires a follow-up request to Sam and team. There's also an "ai_tutor_interactions" table exposed in Trevor - Redshift. If going forward they need to have both of those, then you should think about if and how to link those two together. If this replaces the other, then all the easier and we can go ahead and get rid of ai_tutor_interactions. It has 5 rows right now and all from ~5-6 months ago, so doesn't look like it connects to ai_tutor_interactions_feedback.

**Review by jordan-springer — APPROVED** [review]
LGTM

**Comment by allison-code-dot-org** [comment]
> A couple comments for consideration here:
> 
> * Given the specification above that they will eventually expect students and teachers to be adding feedback, why not bring in user_type at this stage?
> * I see two other feedback tables that are exposed in Trevor - Redshift. Since you're going through the exercise to make a general version of a feedback table, would it make sense to extend that general version and see whether it works for the other two tables as well? That feels like a good way to test the model's ability to generalize across different types of feedback and it's work we would need to do anyway to deprecate Trevor Redshift. Those are:
> 
> 1. lti_feedbacks from Ali (ticket here: https://codedotorg.atlassian.net/browse/DATAOPS-633)
> 2. new_feature_feedbacks from Bryan (ticket here: https://codedotorg.atlassian.net/browse/DATAOPS-738)

For user_type, I originally had this column pulled in from the users table, but the model was taking longer to run when we involve the users table. I decided it was best to leave out the user_type since PMs will know which type of user would be giving feedback about a particular feature, and can always join to dim_students and dim_teachers to grab that field if needed. Didn't seem worth the extra run time. 

Good call out on the additional tables - Sam mentioned there weren't any other feedback tables right now, but she must've not been aware of these. Per your other comment, I was also not aware of that other AI Tutor Interactions table, so will look into that today.

**Review by jordan-springer — APPROVED** [review]

**Pull request merged**
